apiVersion: v1
appVersion: 0.4.0
description: Echo-Server for Kubernetes
home: https://github.com/Ealenn/Echo-Server
icon: https://ealenn.github.io/Echo-Server/assets/images/ping-pong.png
keywords:
- echo
- server
- rest
- test
- api
maintainers:
- name: Rudy Marchandise
name: echo-server
sources:
- https://github.com/Ealenn/Echo-Server
version: 0.3.1
